# Generated by Django 5.0.7 on 2026-04-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['created']},
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
